### ISSUE TITLE
Recipe app

### ISSUE THREAD

**Issue by olawale-o** [olawale-o/our_recipe_app#10]
[Link to Kanban board](https://github.com/olawale-o/our_recipe_app/projects/1)

We are team of 2 people:
- Team member 1: [SimonGrchevski](https://github.com/SimonGrchevski)
- Team member 2: [Olawale-o](https://github.com/olawale-o)

**Comment by descholar-ceo** [comment]
Hi @olawale-o and @SimonGrchevski , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] The cards #11 #9 #8 are missing descriptions, descriptions are better way to define a given task so that it will be easy to be implemented, so I suggest you add them before we move on!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by olawale-o** [comment]
Hi @descholar-ceo 
Thank you for your time.

**Comment by Emmyn5600** [comment]
Hi @olawale-o and @SimonGrchevski 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by olawale-o** [comment]
Hi @Emmyn5600
Thank you for your time and effort on the review
